### ISSUE TITLE
5.2 Outer Join On the Hashed Table 

### ISSUE THREAD

**Issue by cheapcontact** [midsw261/Spring2017#2]
I'm having a hard time coming up with a purely mapper based solution for the outer join on the hashed table.  Assuming that one always wants to hash the smaller table because that's the entire reason you can get away with loading one of your tables into memory, then when we try to do an outer join on that table we have this sort of psuedo code in the mapper for its outer join.

```
def mapper_init(self):
   hashed_table = create_hashed_table(countries_file)
   keys_not_seen_yet = hashed_table.keys()

def mapper(self, _, line):
   key, values = parse(line)
   if key in hashed_table:
      keys_not_seen_yet.remove(key)
      yield key, values

def mapper_final(self):
   for key in keys_not_seen_yet:
      yield key, null
```

This works for a single mapper, but if there is more than one mapper then each mapper will fail to see different keys so you'll get too many results, unless you introduce a reducer that can remove the those extra keys. 

If I weren't worried about memory being taken up by either table it would make sense to put the table getting outer joined as the input file/table and the other table as the hashed file/table, then your results are easy to produce. But I think that defeats the intent of this problem and design pattern since the Mapper Hash Join is pretty explicit about putting the smaller table in the hash. 

Point being I've only thought of three ways to accomplish the join:
1. Only have one mapper (problem: the mapper count settings are only suggestions and might be ignored by Hadoop, and why even use Hadoop if you're not going to parallel-ize at all.)
2. Have a reducer to get rid of extra rows (problem: you're pushing the entire result set plus extras across to the reducer, doesn't seem very optimal)
3. Have the runner filter out the extra rows (Problem: the problem statement says that the MapReduce job is suppose to do the join so having the runner do some essential work, not just printing results, feels like I'm not solving the problem as intended.)

Any guidance is appreciated.

**Comment by anachlas** [comment]
The only solution I was able to come up with used the reducer to emit those unjoined keys.

**Comment by cheapcontact** [comment]
From the grading it looks like it was okay to use a reducer in this one particular join.
