### ISSUE TITLE
5.3 Average Calculations

### ISSUE THREAD

**Issue by cheapcontact** [midsw261/Spring2017#4]
I am getting all of the individual similarity calculations to match those in the expected output but for the first and third data set I'm getting different averages. If I calculate the averages by hand it looks like the expected output has the incorrect averages. For instance:

```
Systems test  3  - Similarity measures
——————————————————————————————————————————————————————————————————————————————————————————————————————————————
        average |           pair |         cosine |        jaccard |        overlap |           dice
--------------------------------------------------------------------------------------------------------------
       0.741582 |    DocA - DocB |       0.816497 |       0.666667 |       1.000000 |       0.800000
```

Calculating the average by hand (which matches my output):
```
(/ (+ 0.816497 0.666667 1.000000 0.800000) 4)
0.820791
```

My averages for System test 2 are perfect matches. Can you confirm or deny that the expected output averages for system test 1 and 3 are incorrect?

**Comment by kyleiwaniec** [comment]
Thanks for pointing that out. The output in the notebook was incorrect - it was from an older example that had not included overlap in the average calculation.

The notebook has been updated:
https://github.com/midsw261/Spring2017/blob/master/HW5/MIDS-W261-HW-05-PHASE1-TEMPLATE.ipynb
